# Generated by Django 3.2.5 on 2021-09-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csvs',
            new_name='csv',
        ),
    ]
