# Generated by Django 3.2.5 on 2021-09-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csv_activated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv',
            new_name='Csvs',
        ),
    ]
