# Generated by Django 3.2.5 on 2021-09-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_csv_csvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg_monthly_price',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
