# Generated by Django 3.2.5 on 2021-09-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_egg_monthly_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg_monthly_price',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
